/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123TopicIdChar125RouteImport } from './routes/{-$topicId}'

const Char123TopicIdChar125Route = Char123TopicIdChar125RouteImport.update({
  id: '/{-$topicId}',
  path: '/{-$topicId}',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$topicId}': typeof Char123TopicIdChar125Route
}
export interface FileRoutesByTo {
  '/{-$topicId}': typeof Char123TopicIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$topicId}': typeof Char123TopicIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/{-$topicId}'
  fileRoutesByTo: FileRoutesByTo
  to: '/{-$topicId}'
  id: '__root__' | '/{-$topicId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123TopicIdChar125Route: typeof Char123TopicIdChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$topicId}': {
      id: '/{-$topicId}'
      path: '/{-$topicId}'
      fullPath: '/{-$topicId}'
      preLoaderRoute: typeof Char123TopicIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123TopicIdChar125Route: Char123TopicIdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
