/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsChar123TopicIdChar125RouteImport } from './routes/topics.{-$topicId}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsChar123TopicIdChar125Route =
  TopicsChar123TopicIdChar125RouteImport.update({
    id: '/topics/{-$topicId}',
    path: '/topics/{-$topicId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/topics/{-$topicId}': typeof TopicsChar123TopicIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/topics/{-$topicId}': typeof TopicsChar123TopicIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/topics/{-$topicId}': typeof TopicsChar123TopicIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/topics/{-$topicId}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/topics/{-$topicId}'
  id: '__root__' | '/' | '/topics/{-$topicId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TopicsChar123TopicIdChar125Route: typeof TopicsChar123TopicIdChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/{-$topicId}': {
      id: '/topics/{-$topicId}'
      path: '/topics/{-$topicId}'
      fullPath: '/topics/{-$topicId}'
      preLoaderRoute: typeof TopicsChar123TopicIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TopicsChar123TopicIdChar125Route: TopicsChar123TopicIdChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
