name: Standard

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  standard:
    name: Standard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Check types
        run: npm run type:check
      - name: Check format, lint and import sorting
        run: npm run check-ci
      - name: Build
        run: npm run build
